# Generated by Django 3.1.7 on 2021-04-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_rating',
            field=models.DecimalField(decimal_places=2, default='3', max_digits=6),
        ),
    ]
